language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: mFib9nCgX2pxXHjhYcZRRJQ1qAA40NH5QBBHb27AIY+6r2zLBkNYQ8N3nCk4lgUiz78el6VKmT3yyKJpJ7EfF6tKg+I7jyCIF7t65whDM9Ks/sV5PWi7oblhHilPH/KBERbdbLDSMFm4xvNtFscSXsDhd68LLsIw4oaXmkZfkbKaW39W7SrV9pemT+aDLlbJeyjCZhD2BG9B2QXaBVEsz58XLbCdMhGsfHGMQSvqd9thJqrHvXZURgEv99JKxAEuixG5cApkIe08QKW4GnLA9AjqePiso7YEl6zDsZinTcCRYpMKrOMlPcad1ewZLpjwG3/J6wy+P1jUgZ4RXpob3h0rKrgV3Td+QlxGKWPX5lJjBdhgPGX3U95E1uxz3Sy6p4hgPnRysWpcZC18BSiXGOrgHw1jvDmK9hEkH2VNMUzwJu4Iopm072JCXipX2mlMZdzsSWdazsTOl8PvlohHiEIjVpl2r8hp24WKE0CIhUk5sw+EITPGTo2TWiQsdD0w69eXGk4hSYXHJMFAsNOwK4igbiGyT13rrULrdpeZN126SfbVsa88iwBmLcclf7iqHhf+WpJHYPrzIpYEj5hHB6SLn+knLIbVLWsKffGFdMmljLY94j/VoGwFpe7uHj7PLSCSgsM6e1EG1gCPZIzoLGK076RryLVDyarnnVOMgl8=
    