language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: vSZrZEiH2zXMjb2pAa4BywBay1fQiI3IxBSaZqU68XS9EQ1DMwkAQrf06rybs9HC8wEtV/rE6Ff7UQytPONkTOSzaVC0X7A8cM0Cl1Hcvhsj28ytJvz8si4P6AtHhNCE7gMMs179bbgIIh7d4TB+4tjNPozR3ULl0UNhi82VJIT1+vl7iWxG8gBog3Glvj4OdvrreulAT3E7a1eM9pUUO6LqAWYcK5bgguzDwAnE0fFskxvYbSiSsmuS3n0GrjzOKocCsnMCq/qlNDQ/llUJ18SST6W/CD+eEL79Uzy5oLmG8r/3rUKOEPJ9wt23d5jdO66HQnldP1oEOmgI6YuAWK6I8sQp2XYy/SNWBZYpu+oZ4+kh2Qq5+zlboLBHZ04zfdrzloMvmcciht2OPR3ocxicQBh0vcTzgU69fAOTn1As7/Hpj5HyjkLp3QYgluBoww0xndijvS93medM+Rjzf9GGBHaVVIQ8dTgJy9NLevfraP4vJIciE/1juFuTMtU5TYz99OYDDOhjGwJov6MMl3VASPXVNFzdK2aHuq91gJ3VPgs9obkafTrnImIOS18EYxbYysr64LQkG4E0s1aRcxsrHsuFRQA5IZcX9Lp3iTy4yONCT3gdb6rxSVTIRyhqF3haydiOgVspDNSQQRN4YWeMWOTc3BPa26f7RJ0x/L4=
