language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: iIh0j2/8uQDv8vZc+VokFz4atY8ZTNDSuUYjpotQbw3EUI4mTx5NNDp9dxAccy9qkk+SzYtCyfqF3uXMtNjIRu/PcawvoeqQR5mLu5MUz6HHmBO6+BYEHAPXqukAhgmaMubasm/JHEFaw1Fmo7SnO3s7EVAKg6cvAa1JNsIGv7D5iWMo4g5aFBQHSwUd97Xwv1jjED2OCVBFmXBnISSaiTgWXRV+xv/Darfb7QXedkT/H4UzGElktYeFHKrNfgDYQ1pGQ+G336F7YLxeRWxSIOBivvblxGHl9TupT4j7GMHsQUtGa2PrTNmTYE9Xj6cRAPh4k/VTy2aSZr9IdxsxNHz4AZ+cLWmWYT24HsCyVgrdaBCEYZsx/QT461eOwp8PDSfMz6QdHHucBwxzbU4XhsjmZNEBg0iztQNJ/DwOtZEV3/bdTKLD7e0YBqiEwQctMBWJKeVWZYR4oCcHDsSgsPOeVSVTQCj2BTFoX9zYukdNDx7Xz7V4hVCFt7FcYU3czD8Ic2USmwJe9Ucn9d3EIaVRJc587hyDI9NuG1VvjDUL7sSp6Zs9vrd9EvxFIYkYUAdjgMon/grpeIrqHLVZdhJFRVhdyPt7SJhDbUsfkrs5ntJIwpGL1TFPBkkfFkegiYAtOEinpvSJH/td7O1VZl63CT77KEUeaG0xT96WANY=
