language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: eyJomRg8Y/XnaC4p0LJAqLUPmNcMcGoguAXSVeLEVEDPU5TDLpsayVHT3JKWU2ZWW2Gyjy4b15rCy1vTlmbIAvKK0BAwBVs0lR7Wmbm0WLtcsky4paU3JiIhZqCDA8326rgaEJx19mUW3XnaHKBzN/fiL7sG5/TF3EqL5NkkxnVgcig2zw1DDxZI1csKhoCr9uWwutYz4Zr9DpCZZq3DuVPHwNr8GGksFstGlm42ARSRjlbyx+9GLdxqC66eyz8BoDZS0mUu0HeZPMtet+k2m/J2RfgwlTwrg2ClX5Tv/klsXjGNWCPhC8z4kIvIWP9Qh+/38krIQ/BVScS/mj5NKicCmrt5lbjGSANN2DODmhLflglabyyO9O+uw4pToVjDsnFJWkZ2ioLscYOTMe+QtbMH7PZInwSCTWUuOXBybvUP9XR1r9DQdVvuC/IDgnwY6s2A03qYYaR9MSVqqKOodbjH+Vu8YTWE/Wfzajif4ucAA4MUv1PHu/tyFcPLGQeIkS8ZIsjdgXdyr/qPf3ka+gCGQeBR7qhuWE1RrMTW/u4IP95sqGA0CKTZi8q9vQIeiOq2vppQGaexslJAJphvrpbLvmAoxykUTkDpM53Pfd6UV9iBcj83baTjA1ktTQL5SaSvU5tA8bJ9CwU7wnmWCAUdVwnwsK5aJJgR58Eqf7U=